# Generated by Django 5.0.7 on 2024-08-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
