# Generated by Django 5.0.7 on 2024-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="None", max_length=100, unique=True),
        ),
    ]
