# Generated by Django 5.0.7 on 2024-08-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="None", max_length=100),
        ),
    ]
